In [1]:
import numpy as np
import pandas as pd

In [2]:
## Função para preparação do holdout (separando classes e dados) ##
def separation_features(dataframe):
    df_features = dataframe.iloc[:, :-1]
    df_classe = dataframe['classe']
    return df_features, df_classe;

## Lendo as bases: 
df1 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_256_max.csv')
df2 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_256_avg.csv')
df3 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_128_max.csv')
df4 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_256_max.csv')
df5 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_128_avg.csv')
df6 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_256_avg.csv')

df7 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG16_256_max.csv')
df8 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG16_256_avg.csv')
df9 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_128_max.csv')
df10 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_256_max.csv')
df11 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_128_avg.csv')
df12 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_256_avg.csv')


X1, y1 = separation_features(df1)
X2, y2 = separation_features(df2)
X3, y3 = separation_features(df3)
X4, y4 = separation_features(df4)
X5, y5 = separation_features(df5)
X6, y6 = separation_features(df6)
X7, y7 = separation_features(df7)
X8, y8 = separation_features(df8)
X9, y9 = separation_features(df9)
X10, y10 = separation_features(df10)
X11, y11 = separation_features(df11)
X12, y12 = separation_features(df12)

In [3]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X7_scaled = scaler.fit_transform(X7)
X8_scaled = scaler.fit_transform(X8)
X9_scaled = scaler.fit_transform(X9)
X10_scaled = scaler.fit_transform(X10)
X11_scaled = scaler.fit_transform(X11)
X12_scaled = scaler.fit_transform(X12)

In [4]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3,shuffle=True, random_state=1)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3,shuffle=True, random_state=1)
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.3,shuffle=True, random_state=1)
X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, test_size=0.3,shuffle=True, random_state=1)
X5_train, X5_test, y5_train, y5_test = train_test_split(X5, y5, test_size=0.3,shuffle=True, random_state=1)
X6_train, X6_test, y6_train, y6_test = train_test_split(X6, y6, test_size=0.3,shuffle=True, random_state=1)
X7_train, X7_test, y7_train, y7_test = train_test_split(X7_scaled, y7, test_size=0.3,shuffle=True, random_state=1)
X8_train, X8_test, y8_train, y8_test = train_test_split(X8_scaled, y8, test_size=0.3,shuffle=True, random_state=1)
X9_train, X9_test, y9_train, y9_test = train_test_split(X9_scaled, y9, test_size=0.3,shuffle=True, random_state=1)
X10_train, X10_test, y10_train, y10_test = train_test_split(X10_scaled , y10, test_size=0.3,shuffle=True, random_state=1)
X11_train, X11_test, y11_train, y11_test = train_test_split(X11_scaled, y11, test_size=0.3,shuffle=True, random_state=1)
X12_train, X12_test, y12_train, y12_test = train_test_split(X12_scaled, y12, test_size=0.3,shuffle=True, random_state=1)

In [5]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn import metrics

gnb = GaussianNB()
mnb = MultinomialNB()
cnb = ComplementNB()

exp_nb = [gnb, mnb, cnb]

def aplicar_NB_holdout(X_train, X_test, y_train, y_test, type_nb):
        type_nb.fit(X_train, y_train)
        y_pred = type_nb.predict(X_test)

        acuracia = metrics.accuracy_score(y_test, y_pred)
        print(f'Metrica: {type_nb}  | Accuracy: %.5f' % acuracia)

        print(confusion_matrix(y_test, y_pred))

def aplicar_NB_kfold(X, y, type_nb, k_fold = 10):
        kf = KFold(n_splits=k_fold, random_state=1, shuffle=True) #Criação do K-fold

        scores = cross_val_score(type_nb, X, y, scoring='accuracy', cv=kf)
        print(f'\nAccuracy (average): %.5f (%.5f) | Metrica: {type_nb} ' % (scores.mean(), scores.std()))
        print(f'Accuracy (average): %.5f {scores}')

        y_pred = cross_val_predict(type_nb, X, y, cv=kf)

In [6]:
datasets = [
    ('cnn_VGG16_256_max', X1_train, X1_test, y1_train, y1_test),
    ('cnn_VGG16_256_avg', X2_train, X2_test, y2_train, y2_test),
    ('cnn_VGG19_128_max', X3_train, X3_test, y3_train, y3_test),
    ('cnn_VGG19_256_max', X4_train, X4_test, y4_train, y4_test),
    ('cnn_VGG19_128_avg', X5_train, X5_test, y5_train, y5_test),
    ('cnn_VGG19_256_avg', X6_train, X6_test, y6_train, y6_test),
    ('PCA_cnn_VGG16_256_max', X7_train, X7_test, y7_train, y7_test),
    ('PCA_cnn_VGG16_256_avg', X8_train, X8_test, y8_train, y8_test),
    ('PCA_cnn_VGG19_128_max', X9_train, X9_test, y9_train, y9_test),
    ('PCA_cnn_VGG19_256_max', X10_train, X10_test, y10_train, y10_test),
    ('PCA_cnn_VGG19_128_avg', X11_train, X11_test, y11_train, y11_test),
    ('PCA_cnn_VGG19_256_avg', X12_train, X12_test, y12_train, y12_test),
]

In [7]:
for name, X_train, X_test, y_train, y_test in datasets:
    print(f"\n--------------------- {name} ---------------------")
    for exp in exp_nb:
        aplicar_NB_holdout(X_train, X_test, y_train, y_test, exp)



--------------------- cnn_VGG16_256_max ---------------------
Metrica: GaussianNB()  | Accuracy: 0.97490
[[62  0  1  1]
 [ 0 54  2  1]
 [ 0  0 65  0]
 [ 0  1  0 52]]
Metrica: MultinomialNB()  | Accuracy: 0.98326
[[63  0  1  0]
 [ 0 55  1  1]
 [ 0  0 65  0]
 [ 0  1  0 52]]
Metrica: ComplementNB()  | Accuracy: 0.97071
[[64  0  0  0]
 [ 0 56  0  1]
 [ 2  2 61  0]
 [ 1  1  0 51]]

--------------------- cnn_VGG16_256_avg ---------------------
Metrica: GaussianNB()  | Accuracy: 0.95816
[[62  0  2  0]
 [ 0 55  1  1]
 [ 0  3 62  0]
 [ 0  2  1 50]]
Metrica: MultinomialNB()  | Accuracy: 0.98326
[[64  0  0  0]
 [ 0 54  2  1]
 [ 0  0 65  0]
 [ 0  1  0 52]]
Metrica: ComplementNB()  | Accuracy: 0.98745
[[64  0  0  0]
 [ 0 56  0  1]
 [ 0  0 65  0]
 [ 1  1  0 51]]

--------------------- cnn_VGG19_128_max ---------------------
Metrica: GaussianNB()  | Accuracy: 0.92887
[[62  0  0  2]
 [ 0 50  3  4]
 [ 0  3 62  0]
 [ 1  4  0 48]]
Metrica: MultinomialNB()  | Accuracy: 0.94979
[[64  0  0  0]
 [ 0 52  2  

In [8]:
datasets_kfold = [
    ('cnn_VGG16_256_max', X1, y1),
    ('cnn_VGG16_256_avg', X2, y2),
    ('cnn_VGG19_128_max', X3, y3),
    ('cnn_VGG19_256_max', X4, y4),
    ('cnn_VGG19_128_avg', X5, y5),
    ('cnn_VGG19_256_avg', X6, y6),
    ('PCA_cnn_VGG16_256_max', X7_scaled, y7),
    ('PCA_cnn_VGG16_256_avg', X8_scaled, y8),
    ('PCA_cnn_VGG19_128_max', X9_scaled, y9),
    ('PCA_cnn_VGG19_256_max', X10_scaled, y10),
    ('PCA_cnn_VGG19_128_avg', X11_scaled, y11),
    ('PCA_cnn_VGG19_256_avg', X12_scaled, y12),
]

In [9]:
for name, X, y in datasets_kfold:
    print(f"\n--------------------- {name} (K-Fold) ---------------------")
    for exp in exp_nb:
        aplicar_NB_kfold(X, y, exp)


--------------------- cnn_VGG16_256_max (K-Fold) ---------------------

Accuracy (average): 0.97228 (0.01476) | Metrica: GaussianNB() 
Accuracy (average): %.5f [0.9625     0.975      0.9875     1.         0.975      0.96202532
 0.94936709 0.96202532 0.98734177 0.96202532]

Accuracy (average): 0.98239 (0.01002) | Metrica: MultinomialNB() 
Accuracy (average): %.5f [0.9875     0.975      0.9875     1.         0.9625     0.97468354
 0.98734177 0.97468354 0.98734177 0.98734177]

Accuracy (average): 0.97108 (0.01689) | Metrica: ComplementNB() 
Accuracy (average): %.5f [0.975      0.9625     0.9875     0.9875     0.9375     0.98734177
 0.96202532 0.98734177 0.97468354 0.94936709]

--------------------- cnn_VGG16_256_avg (K-Fold) ---------------------

Accuracy (average): 0.96218 (0.02272) | Metrica: GaussianNB() 
Accuracy (average): %.5f [0.9625     0.975      0.9875     0.975      0.975      0.93670886
 0.94936709 0.96202532 0.98734177 0.91139241]

Accuracy (average): 0.98744 (0.00972) | Me