In [2]:
import numpy as np
import pandas as pd

In [3]:
## Função para preparação do holdout (separando classes e dados) ##
def separation_features(dataframe):
    df_features = dataframe.iloc[:, :-1]
    df_classe = dataframe['classe']
    return df_features, df_classe;

## Lendo as bases: 
df1 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_256_max.csv')
df2 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_256_avg.csv')
df3 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_128_max.csv')
df4 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_256_max.csv')
df5 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_128_avg.csv')
df6 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_256_avg.csv')

df7 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG16_256_max.csv')
df8 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG16_256_avg.csv')
df9 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_128_max.csv')
df10 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_256_max.csv')
df11 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_128_avg.csv')
df12 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_256_avg.csv')


X1, y1 = separation_features(df1)
X2, y2 = separation_features(df2)
X3, y3 = separation_features(df3)
X4, y4 = separation_features(df4)
X5, y5 = separation_features(df5)
X6, y6 = separation_features(df6)
X7, y7 = separation_features(df7)
X8, y8 = separation_features(df8)
X9, y9 = separation_features(df9)
X10, y10 = separation_features(df10)
X11, y11 = separation_features(df11)
X12, y12 = separation_features(df12)

In [4]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3,shuffle=True, random_state=1)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3,shuffle=True, random_state=1)
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.3,shuffle=True, random_state=1)
X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, test_size=0.3,shuffle=True, random_state=1)
X5_train, X5_test, y5_train, y5_test = train_test_split(X5, y5, test_size=0.3,shuffle=True, random_state=1)
X6_train, X6_test, y6_train, y6_test = train_test_split(X6, y6, test_size=0.3,shuffle=True, random_state=1)
X7_train, X7_test, y7_train, y7_test = train_test_split(X7, y7, test_size=0.3,shuffle=True, random_state=1)
X8_train, X8_test, y8_train, y8_test = train_test_split(X8, y8, test_size=0.3,shuffle=True, random_state=1)
X9_train, X9_test, y9_train, y9_test = train_test_split(X9, y9, test_size=0.3,shuffle=True, random_state=1)
X10_train, X10_test, y10_train, y10_test = train_test_split(X10, y10, test_size=0.3,shuffle=True, random_state=1)
X11_train, X11_test, y11_train, y11_test = train_test_split(X11, y11, test_size=0.3,shuffle=True, random_state=1)
X12_train, X12_test, y12_train, y12_test = train_test_split(X12, y12, test_size=0.3,shuffle=True, random_state=1)


In [9]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn import metrics

bgDT10 = AdaBoostClassifier(estimator=GaussianNB(), n_estimators=10)
bgDT20 = AdaBoostClassifier(estimator=GaussianNB(), n_estimators=20)
bgDT30 = AdaBoostClassifier(estimator=GaussianNB(), n_estimators=30)

baggings = [bgDT10, bgDT20, bgDT30]

def aplicar_bagging_holdout(X_train, X_test, y_train, y_test, bagging):
        bagging.fit(X_train, y_train)
        y_pred = bagging.predict(X_test)

        acuracia = metrics.accuracy_score(y_test, y_pred)
        print(f'Metrica: {bagging}  | Accuracy: %.5f' % acuracia)

        print(confusion_matrix(y_test, y_pred))

def aplicar_bagging_kfold(X, y, bagging, k_fold=10):
    kf = KFold(n_splits=k_fold, random_state=1, shuffle=True)

    scores = cross_val_score(bagging, X, y, scoring='accuracy', cv=kf)
    print(f'\nMétrica: {bagging.estimator.__class__.__name__}')
    print(f'Accuracy média: %.5f ± %.5f' % (scores.mean(), scores.std()))

    y_pred = cross_val_predict(bagging, X, y, cv=kf)
    print(confusion_matrix(y, y_pred))


In [10]:
datasets = [
    ('cnn_VGG16_256_max', X1_train, X1_test, y1_train, y1_test),
    ('cnn_VGG16_256_avg', X2_train, X2_test, y2_train, y2_test),
    ('cnn_VGG19_128_max', X3_train, X3_test, y3_train, y3_test),
    ('cnn_VGG19_256_max', X4_train, X4_test, y4_train, y4_test),
    ('cnn_VGG19_128_avg', X5_train, X5_test, y5_train, y5_test),
    ('cnn_VGG19_256_avg', X6_train, X6_test, y6_train, y6_test),
    ('PCA_cnn_VGG16_256_max', X7_train, X7_test, y7_train, y7_test),
    ('PCA_cnn_VGG16_256_avg', X8_train, X8_test, y8_train, y8_test),
    ('PCA_cnn_VGG19_128_max', X9_train, X9_test, y9_train, y9_test),
    ('PCA_cnn_VGG19_256_max', X10_train, X10_test, y10_train, y10_test),
    ('PCA_cnn_VGG19_128_avg', X11_train, X11_test, y11_train, y11_test),
    ('PCA_cnn_VGG19_256_avg', X12_train, X12_test, y12_train, y12_test),
]

In [11]:
for name, X_train, X_test, y_train, y_test in datasets:
    print(f"\n--------------------- {name} ---------------------")
    for exp in baggings:
        aplicar_bagging_holdout(X_train, X_test, y_train, y_test, exp)



--------------------- cnn_VGG16_256_max ---------------------
Metrica: AdaBoostClassifier(estimator=GaussianNB(), n_estimators=10)  | Accuracy: 0.97071
[[61  0  1  2]
 [ 0 54  2  1]
 [ 0  0 65  0]
 [ 0  1  0 52]]
Metrica: AdaBoostClassifier(estimator=GaussianNB(), n_estimators=20)  | Accuracy: 0.97071
[[61  0  1  2]
 [ 0 55  1  1]
 [ 0  1 64  0]
 [ 0  1  0 52]]
Metrica: AdaBoostClassifier(estimator=GaussianNB(), n_estimators=30)  | Accuracy: 0.97490
[[62  0  1  1]
 [ 0 55  1  1]
 [ 0  1 64  0]
 [ 0  1  0 52]]

--------------------- cnn_VGG16_256_avg ---------------------
Metrica: AdaBoostClassifier(estimator=GaussianNB(), n_estimators=10)  | Accuracy: 0.95816
[[62  0  2  0]
 [ 0 55  1  1]
 [ 0  3 62  0]
 [ 0  2  1 50]]
Metrica: AdaBoostClassifier(estimator=GaussianNB(), n_estimators=20)  | Accuracy: 0.95816
[[62  0  2  0]
 [ 0 55  1  1]
 [ 0  3 62  0]
 [ 0  2  1 50]]
Metrica: AdaBoostClassifier(estimator=GaussianNB(), n_estimators=30)  | Accuracy: 0.95816
[[62  0  2  0]
 [ 0 55  1  1]