In [19]:
import pandas as pd
import numpy as np

In [20]:
## Função para preparação do holdout (separando classes e dados) ##
def separation_features(dataframe):
    df_features = dataframe.iloc[:, :-1]
    df_classe = dataframe['classe']
    return df_features, df_classe;

## Lendo as bases: 
df1 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_256_max.csv')
df2 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_256_avg.csv')
df3 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_128_max.csv')
df4 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_256_max.csv')
df5 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_128_avg.csv')
df6 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_256_avg.csv')

df7 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG16_256_max.csv')
df8 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG16_256_avg.csv')
df9 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_128_max.csv')
df10 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_256_max.csv')
df11 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_128_avg.csv')
df12 = pd.read_csv('../Dados/PCA_Features/PCA_cnn_VGG19_256_avg.csv')


X1, y1 = separation_features(df1)
X2, y2 = separation_features(df2)
X3, y3 = separation_features(df3)
X4, y4 = separation_features(df4)
X5, y5 = separation_features(df5)
X6, y6 = separation_features(df6)
X7, y7 = separation_features(df7)
X8, y8 = separation_features(df8)
X9, y9 = separation_features(df9)
X10, y10 = separation_features(df10)
X11, y11 = separation_features(df11)
X12, y12 = separation_features(df12)

In [21]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3,shuffle=True, random_state=1)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3,shuffle=True, random_state=1)
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.3,shuffle=True, random_state=1)
X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, test_size=0.3,shuffle=True, random_state=1)
X5_train, X5_test, y5_train, y5_test = train_test_split(X5, y5, test_size=0.3,shuffle=True, random_state=1)
X6_train, X6_test, y6_train, y6_test = train_test_split(X6, y6, test_size=0.3,shuffle=True, random_state=1)
X7_train, X7_test, y7_train, y7_test = train_test_split(X7, y7, test_size=0.3,shuffle=True, random_state=1)
X8_train, X8_test, y8_train, y8_test = train_test_split(X8, y8, test_size=0.3,shuffle=True, random_state=1)
X9_train, X9_test, y9_train, y9_test = train_test_split(X9, y9, test_size=0.3,shuffle=True, random_state=1)
X10_train, X10_test, y10_train, y10_test = train_test_split(X10, y10, test_size=0.3,shuffle=True, random_state=1)
X11_train, X11_test, y11_train, y11_test = train_test_split(X11, y11, test_size=0.3,shuffle=True, random_state=1)
X12_train, X12_test, y12_train, y12_test = train_test_split(X12, y12, test_size=0.3,shuffle=True, random_state=1)


In [26]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder

In [30]:
bst1 = XGBClassifier(n_estimators=100, max_depth=5, learning_rate=0.1, eval_metric='mlogloss')
bst2 = XGBClassifier(n_estimators=300, max_depth=4, learning_rate=0.03, eval_metric='mlogloss')

bsts = [bst1, bst2]

def aplicar_XGB_holdout(X_train, X_test, y_train, y_test, bst):
        le = LabelEncoder()
        y_train_encoded = le.fit_transform(y_train)
        y_test_encoded = le.transform(y_test)
        bst.fit(X_train, y_train_encoded)
        y_pred = bst.predict(X_test)

        acuracia = metrics.accuracy_score(y_test_encoded, y_pred)
        print(f'Metrica: {bst}  | Accuracy: %.5f' % acuracia)

        print(confusion_matrix(y_test_encoded, y_pred))

In [31]:
datasets = [
    ('cnn_VGG16_256_max', X1_train, X1_test, y1_train, y1_test),
    ('cnn_VGG16_256_avg', X2_train, X2_test, y2_train, y2_test),
    ('cnn_VGG19_128_max', X3_train, X3_test, y3_train, y3_test),
    ('cnn_VGG19_256_max', X4_train, X4_test, y4_train, y4_test),
    ('cnn_VGG19_128_avg', X5_train, X5_test, y5_train, y5_test),
    ('cnn_VGG19_256_avg', X6_train, X6_test, y6_train, y6_test),
    ('PCA_cnn_VGG16_256_max', X7_train, X7_test, y7_train, y7_test),
    ('PCA_cnn_VGG16_256_avg', X8_train, X8_test, y8_train, y8_test),
    ('PCA_cnn_VGG19_128_max', X9_train, X9_test, y9_train, y9_test),
    ('PCA_cnn_VGG19_256_max', X10_train, X10_test, y10_train, y10_test),
    ('PCA_cnn_VGG19_128_avg', X11_train, X11_test, y11_train, y11_test),
    ('PCA_cnn_VGG19_256_avg', X12_train, X12_test, y12_train, y12_test),
]

In [32]:
for name, X_train, X_test, y_train, y_test in datasets:
    print(f"\n--------------------- {name} ---------------------")
    for bst in bsts:
        aplicar_XGB_holdout(X_train, X_test, y_train, y_test, bst)



--------------------- cnn_VGG16_256_max ---------------------
Metrica: XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)  | Accuracy: 0.97908
[[63  0  1  0]
 [ 0 57  0  0]
 [ 0  1 64  0]
 [ 0  3  0 50]]
Metrica: XGBClassifier(base_score=None, booster=None, callbacks=None,
