In [3]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

In [5]:
df1 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_128_max.csv')
df2 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_128_avg.csv')
df3 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_256_max.csv')
df4 = pd.read_csv('../Dados/CNN_Features/cnn_VGG16_256_avg.csv')
df5 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_128_max.csv')
df6 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_128_avg.csv')
df7 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_256_avg.csv')
df8 = pd.read_csv('../Dados/CNN_Features/cnn_VGG19_256_max.csv')

print(f"CNN_VGG16_128-max:{df1.shape} \nCNN_VGG16_128-avg:{df2.shape} \nCNN_VGG16_256-max: {df3.shape} \n CNN_VGG16_256-avg: {df4.shape}\nCNN_VGG19_128-max: {df5.shape} \nCNN_VGG19_128-avg: {df6.shape} \nCNN_VGG19_256-max: {df7.shape} \nCNN_VGG19_256-avg: {df8.shape}")

## Função de preparação dos dados para aplicar o HOLDOUT ##
def preparation_holdout(dataframe):
    df_features = dataframe.iloc[:, :-1]
    df_classe = dataframe['classe']

    return df_features, df_classe;

X1, y1 = preparation_holdout(df1)
X2, y2 = preparation_holdout(df2)
X3, y3 = preparation_holdout(df3)
X4, y4 = preparation_holdout(df4)
X5, y5 = preparation_holdout(df5)
X6, y6 = preparation_holdout(df6)
X7, y7 = preparation_holdout(df7)
X8, y8 = preparation_holdout(df8)

CNN_VGG16_128-max:(795, 513) 
CNN_VGG16_128-avg:(795, 513) 
CNN_VGG16_256-max: (795, 513) 
 CNN_VGG16_256-avg: (795, 513)
CNN_VGG19_128-max: (795, 513) 
CNN_VGG19_128-avg: (795, 513) 
CNN_VGG19_256-max: (795, 513) 
CNN_VGG19_256-avg: (795, 513)


In [6]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3,shuffle=True, random_state=1)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3,shuffle=True, random_state=1)
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.3,shuffle=True, random_state=1)
X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, test_size=0.3,shuffle=True, random_state=1)
X5_train, X5_test, y5_train, y5_test = train_test_split(X5, y5, test_size=0.3,shuffle=True, random_state=1)
X6_train, X6_test, y6_train, y6_test = train_test_split(X6, y6, test_size=0.3,shuffle=True, random_state=1)
X7_train, X7_test, y7_train, y7_test = train_test_split(X7, y7, test_size=0.3,shuffle=True, random_state=1)
X8_train, X8_test, y8_train, y8_test = train_test_split(X8, y8, test_size=0.3,shuffle=True, random_state=1)

In [7]:
## Aplica CNN nos dataframe
def aplicar_KNN(X_train, X_test, y_train, y_test, k_range = 10):
    for i in range(1, k_range + 1):
        kNN = KNeighborsClassifier(n_neighbors=i, metric='euclidean') 
        kNN.fit(X_train, y_train)
    
        y_pred = kNN.predict(X_test)
        print(f"Accuracy k = {i}:",metrics.accuracy_score(y_test, y_pred))
        print(confusion_matrix(y_test, y_pred))
        

## CNN_VGG16_128-max #
print("\nCNN_VGG16_128-max:")
aplicar_KNN(X1_train, X1_test, y1_train, y1_test)

## CNN_VGG16_128-avg #
print("\nCNN_VGG16_128-avg:")
aplicar_KNN(X2_train, X2_test, y2_train, y2_test)

## CNN_VGG16_256-max #
print("\nCNN_VGG16_256-max:")
aplicar_KNN(X3_train, X3_test, y3_train, y3_test)

# CNN_VGG16_256-avg #
print("\nCNN_VGG16_256-avg:")
aplicar_KNN(X4_train, X4_test, y4_train, y4_test)
    



CNN_VGG16_128-max:
Accuracy k = 1: 0.899581589958159
[[61  0  3  0]
 [ 1 49  5  2]
 [ 0  3 61  1]
 [ 2  5  2 44]]
Accuracy k = 2: 0.9037656903765691
[[61  1  2  0]
 [ 1 52  4  0]
 [ 0  3 62  0]
 [ 2  8  2 41]]
Accuracy k = 3: 0.9163179916317992
[[61  0  3  0]
 [ 1 50  6  0]
 [ 0  3 62  0]
 [ 2  3  2 46]]
Accuracy k = 4: 0.9163179916317992
[[63  0  1  0]
 [ 1 53  3  0]
 [ 1  6 58  0]
 [ 2  4  2 45]]
Accuracy k = 5: 0.9330543933054394
[[64  0  0  0]
 [ 1 52  4  0]
 [ 0  4 61  0]
 [ 2  3  2 46]]
Accuracy k = 6: 0.9372384937238494
[[64  0  0  0]
 [ 1 54  2  0]
 [ 1  5 59  0]
 [ 1  2  3 47]]
Accuracy k = 7: 0.9497907949790795
[[64  0  0  0]
 [ 1 52  4  0]
 [ 0  1 64  0]
 [ 1  2  3 47]]
Accuracy k = 8: 0.9330543933054394
[[63  0  1  0]
 [ 1 52  4  0]
 [ 0  3 62  0]
 [ 1  3  3 46]]
Accuracy k = 9: 0.9330543933054394
[[63  0  1  0]
 [ 0 51  6  0]
 [ 0  1 64  0]
 [ 1  4  3 45]]
Accuracy k = 10: 0.9246861924686193
[[63  0  1  0]
 [ 1 52  4  0]
 [ 0  4 61  0]
 [ 1  4  3 45]]

CNN_VGG16_128-avg:


In [ ]:
# CNN_VGG19_128-max #
print("\nCNN_VGG19_128-max:")
aplicar_KNN(X5_train, X5_test, y5_train, y5_test)

# CNN_VGG19_128-avg #
print("\nCNN_VGG19_128-avg:")
aplicar_KNN(X6_train, X6_test, y6_train, y6_test)

# CNN_VGG19_256-max #
print("\nCNN_VGG19_256-max:")
aplicar_KNN(X7_train, X7_test, y7_train, y7_test)

# CNN_VGG16_256-avg #
print("\nCNN_VGG19_256-avg:")
aplicar_KNN(X8_train, X8_test, y8_train, y8_test)

In [ ]:
def aplicar_KNN_with_kfold(X, y, k_range = 10, k_fold = 10):
    kf = KFold(n_splits= k_fold, random_state=1, shuffle=True)
    for i in range(1, k_range + 1):
        kNN = KNeighborsClassifier(n_neighbors=i, metric='euclidean') 
        scores = cross_val_score(kNN, X, y, scoring='accuracy', cv=kf)
        print(f'\nAccuracy (average): %.5f (%.5f) | k = {i}' % (scores.mean(), scores.std()))
        print(f'Accuracy (average): %.5f | k = {i} {scores}')

        y_pred = cross_val_predict(kNN, X, y, cv=kf)
        print(confusion_matrix(y, y_pred))

print("\n10-Fold - CNN_VGG16_128-max: ")
aplicar_KNN_with_kfold( X = X1, y = y1)

print("\n10-Fold - CNN_VGG16_128-avg: ")
aplicar_KNN_with_kfold(X = X2, y = y2)

print("\n10-Fold - CNN_VGG16_256-max: ")
aplicar_KNN_with_kfold(X = X3, y = y3)

print("\n10-Fold - CNN_VGG16_256-avg: ")
aplicar_KNN_with_kfold(X = X4, y = y4)

print("\n10-Fold - CNN_VGG19_128-max: ")
aplicar_KNN_with_kfold(X = X5, y = y5)

print("\n10-Fold - CNN_VGG19_128-avg: ")
aplicar_KNN_with_kfold(X = X6, y = y6)

print("\n10-Fold - CNN_VGG19_256-max: ")
aplicar_KNN_with_kfold(X = X7, y = y7)

print("\n10-Fold - CNN_VGG19_256-avg: ")
aplicar_KNN_with_kfold(X = X8, y = y8)

