In [8]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [9]:
## LENDO AS BASES HOGS E DEFININDO X E y PARA HOLDOUT ##
df1 = pd.read_csv('../Dados/HOG_Features/HOG_128_16x16.csv')
df2 = pd.read_csv('../Dados/Hog_Features/HOG_128_20x20.csv')
df3 = pd.read_csv('../Dados/Hog_Features/HOG_256_16x16.csv')
df4 = pd.read_csv('../Dados/Hog_Features/HOG_256_20x20.csv')

print(f"df1:{df1.shape} | df2:{df2.shape} | df3:{df3.shape} | df4:{df4.shape}")

def preparation_holdout(dataframe):
    df_features = dataframe.iloc[:, :-1]
    df_classe = dataframe['classe']

    return df_features, df_classe;

X1, y1 = preparation_holdout(df1)
X2, y2 = preparation_holdout(df2)
X3, y3 = preparation_holdout(df3)
X4, y4 = preparation_holdout(df4)

df1:(795, 1765) | df2:(795, 901) | df3:(795, 8101) | df4:(795, 4357)


In [10]:
## Treinamento e Teste: Holdout ##
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3,shuffle=True, random_state=1)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3,shuffle=True, random_state=1)
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.3,shuffle=True, random_state=1)
X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, test_size=0.3,shuffle=True, random_state=1)

In [11]:
def aplicar_KNN_with_Holdout(X_train, X_test, y_train, y_test, k_range = 10):
    for i in range(1,  k_range + 1):
        kNN = KNeighborsClassifier(n_neighbors=i, metric='euclidean') 
        kNN.fit(X_train, y_train)
    
        y_pred = kNN.predict(X_test)
        print(f"Accuracy k = {i}:",metrics.accuracy_score(y_test, y_pred))
        print(confusion_matrix(y_test, y_pred))

## hog_128_16x16 ##
print("\nhog_128_16x16:")
aplicar_KNN_with_Holdout(X1_train, X1_test, y1_train, y1_test)

print("\n-------------------------------------------------------------------------------------------")

## hog_128_20x20 ##
print("\nhog_128_20x20:")
aplicar_KNN_with_Holdout(X2_train, X2_test, y2_train, y2_test)

print("\n-------------------------------------------------------------------------------------------")

## hog_256_16x16 ##
print("\nhog_256_16x16:")
aplicar_KNN_with_Holdout(X3_train, X3_test, y3_train, y3_test)

print("\n-------------------------------------------------------------------------------------------")

## hog_256_20x20 ##
print("\nhog_256_20x20:")
aplicar_KNN_with_Holdout(X4_train, X4_test, y4_train, y4_test)


hog_128_16x16:
Accuracy k = 1: 0.3054393305439331
[[30  8  1 25]
 [11 10  4 32]
 [19 16  5 25]
 [13  9  3 28]]
Accuracy k = 2: 0.3598326359832636
[[45  6  0 13]
 [17 22  3 15]
 [29 20  4 12]
 [23 13  2 15]]
Accuracy k = 3: 0.32217573221757323
[[28  5  0 31]
 [14 17  2 24]
 [24 13  2 26]
 [15  7  1 30]]
Accuracy k = 4: 0.3472803347280335
[[29  3  2 30]
 [ 9 25  1 22]
 [17 24  1 23]
 [15  9  1 28]]
Accuracy k = 5: 0.3263598326359833
[[26  8  2 28]
 [12 25  0 20]
 [17 20  1 27]
 [16 10  1 26]]
Accuracy k = 6: 0.301255230125523
[[19  4  2 39]
 [12 22  0 23]
 [20 19  0 26]
 [12  9  1 31]]
Accuracy k = 7: 0.32217573221757323
[[17  6  0 41]
 [ 7 26  0 24]
 [13 22  0 30]
 [10  8  1 34]]
Accuracy k = 8: 0.32217573221757323
[[16  9  0 39]
 [ 6 29  0 22]
 [14 22  0 29]
 [10 10  1 32]]
Accuracy k = 9: 0.28870292887029286
[[14  8  1 41]
 [ 8 21  0 28]
 [15 20  0 30]
 [10  8  1 34]]
Accuracy k = 10: 0.3179916317991632
[[14 12  1 37]
 [ 7 25  0 25]
 [16 20  0 29]
 [ 7  8  1 37]]

-------------------

In [12]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

In [13]:
def aplicar_KNN_with_kfold(X, y, k_range = 10, k_fold = 10):
    kf = KFold(n_splits=k_fold, random_state=1, shuffle=True)
    for i in range(1, k_range + 1):
         kNN = KNeighborsClassifier(n_neighbors=i, metric='euclidean') 
         scores = cross_val_score(kNN, X, y, scoring='accuracy', cv=kf)
         print(f'\nAccuracy: %.5f (%.5f) k = {i}' % (scores.mean(), scores.std()))
         print("Cross-val accuracies:", scores)

         y_pred = cross_val_predict(kNN, X, y, cv=kf)
         print(confusion_matrix(y, y_pred))

# Model Accuracy
print("\nhog_128_16x16:")
aplicar_KNN_with_kfold(X1, y1)

print("\n-------------------------------------------------------------------------------------------")

print("\nhog_128_20x20:")
aplicar_KNN_with_kfold(X2, y2)

print("\n-------------------------------------------------------------------------------------------")

print("\nhog_256_16x16:")
aplicar_KNN_with_kfold(X3, y3)

print("\n-------------------------------------------------------------------------------------------")

print("\nhog_256_20x20:")
aplicar_KNN_with_kfold(X4, y4)



hog_128_20x20:

Accuracy: 0.35731 (0.05356) k = 1
Cross-val accuracies: [0.325      0.2875     0.3375     0.45       0.325      0.41772152
 0.30379747 0.36708861 0.43037975 0.32911392]
[[ 97  41   3  54]
 [ 38  72   7  83]
 [ 57  64  14  65]
 [ 40  54   5 101]]

Accuracy: 0.37744 (0.04976) k = 2
Cross-val accuracies: [0.2875     0.3375     0.4125     0.45       0.3375     0.37974684
 0.32911392 0.43037975 0.41772152 0.39240506]
[[136  32   2  25]
 [ 60  92   5  43]
 [ 96  74   7  23]
 [ 67  65   3  65]]

Accuracy: 0.35348 (0.03809) k = 3
Cross-val accuracies: [0.3375     0.2875     0.3625     0.3875     0.375      0.36708861
 0.3164557  0.30379747 0.39240506 0.40506329]
[[111  29   0  55]
 [ 56  71   2  71]
 [ 92  57   1  50]
 [ 58  43   1  98]]

Accuracy: 0.34976 (0.03242) k = 4
Cross-val accuracies: [0.3125     0.3        0.325      0.4        0.35       0.35443038
 0.34177215 0.34177215 0.40506329 0.36708861]
[[ 93  35   1  66]
 [ 39  82   1  78]
 [ 68  72   3  57]
 [ 52  47   1 10